language: python
matrix:
  include:
    - name: Linux
      os : linux
      sudo: required
      install:
        - sudo apt-get install python3-venv
        - alias python3=python
        - alias pip="python3 -m pip"
      env:
        - PATH=$PATH:/home/travis/virtualenv/python3.6.7/bin
      before_deploy:
        - cp dist/albion-online-stats albion-online-stats-linux
    - name: macOS
      os: osx
      language: generic
      before_deploy:
        - cp dist/albion-online-stats albion-online-stats-osx

script:
  - python3 --version
  - pip --version
  - python3 -m venv env
  - . env/bin/activate
  - python3 --version
  - python3 -m pip --version
  - python3 -m pip install -r requirements.txt
  - pyinstaller -F -w -i assets/albion-stats-icon.ico --add-data src/assets:src/assets albion-online-stats.py
  - deactivate

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: albion-online-stats-*
  skip_cleanup: true
  on:
    tags: true
