language: rust
rust:
  - nightly
jobs:
  include:
    - os: linux
      dist: xenial
      python: 3.7
      script:
        - sudo add-apt-repository ppa:deadsnakes/ppa -y
        - sudo apt-get update
        - sudo apt-get install -y python3.7 libpython3.7-dev
        - python3.7 -m ensurepip
        - python3.7 -m pip install venv
        - python3.7 -m venv env
        - . env/bin/activate
        - pip install -v -r application/requirements.txt
        - pyinstaller -F -w -i assets/albion-stats-icon.ico --add-data application/src/assets:src/assets application/albion-online-stats.py
        - deactivate
      before_deploy:
        - cp dist/albion-online-stats albion-online-stats-linux
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file:
          - albion-online-stats-linux
        skip_cleanup: true
        on:
          tags: true
    - os: osx
      script:
        - python3 -m venv env
        - . env/bin/activate
        - pip install -v -r application/requirements.txt
        - pyinstaller -F -w -i assets/albion-stats-icon.ico --add-data application/src/assets:src/assets application/albion-online-stats.py
        - deactivate
      before_deploy:
        - cp dist/albion-online-stats albion-online-stats-osx
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file:
          - albion-online-stats-osx
        skip_cleanup: true
        on:
          tags: true
